name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Retry Docker build up to 3 times
      run: |
        TAG=notebooklm:$(date +%s)
        for i in 1 2 3; do
          echo "Attempt $i to build Docker image..."
          docker build --pull . --file Dockerfile --tag $TAG && break || {
            echo "Build failed on attempt $i"
            sleep 15
          }
        done
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/notebooklm
        
        # Build the Docker image
        docker build -t $IMAGE_NAME:latest .
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        
        # Push the images
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
