name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Retry Docker build up to 3 times
      run: |
        TAG=notebookLM:$(date +%s)
        for i in 1 2 3; do
          echo "Attempt $i to build Docker image..."
          docker build --pull . --file Dockerfile --tag $TAG && break || {
            echo "Build failed on attempt $i"
            sleep 15
          }
        done
